### PR TITLE
Merges #9, #13, #15, #24, fixes #21, #34

### LINKED ISSUE #21: The pddl-parser seems to reject empty effects without conjunctions
This definition failed to parse:
```
(:ACTION DIVERGENCE
          :PARAMETERS () ; (?P ?O)
          :PRECONDITION ()
          :EFFECT ())
```
but this one succeeded:
```
(:ACTION DIVERGENCE
          :PARAMETERS () ; (?P ?O)
          :PRECONDITION ()
          :EFFECT (AND))
```
If I understand the syntax correctly, an empty effect as in the first example, seems to be explicitly accepted.

### PR DESCRIPTION
**Pull request by guicho271828**
Merges #9, #13, #15, #24, fixes #21, address #22.
By merging this PR, all other pull-requests can be closed.

### CODE REVIEW

**Comment by jan-dolejsi** [comment]
Dear VAL supporters. We've recently managed to re-merge a large fork (see https://github.com/KCL-Planning/VAL/pull/42) and in the process resolved many popular requests, did a major clean-up and made things ready for continuous integration, which will help us safely service future pull requests. We've also setup a [build pipeline](https://dev.azure.com/schlumberger/ai-planning-validation) to democratize binaries for Linux, Windows and MacOS users.
 
We understand that resolving merge conflicts in your forks may be difficult and will cause some short term pain, but we believe this is a good investment for the future of the project and hope to see your future contributions into this cleaned-up codebase!

**Comment by guicho271828** [comment]
Switching to CMake to allow Windows build ...
Given its (personal opinion: unnecessary) complexity, I think it is a bit difficult to justify because eventually programs like VAL are combined with planners like Fast Downward, which requires Linux or Mac usually.

**Comment by maltehelmert** [comment]
> Switching to CMake to allow Windows build ...
> Given its (personal opinion: unnecessary) complexity, I think it is a bit difficult to justify because eventually programs like VAL are combined with planners like Fast Downward, which requires Linux or Mac usually.

Fast Downward has required CMake since 2015 and has worked on Windows, Mac and Linux for ages.

**Comment by DerekLong101** [comment]
VAL is being used in a Windows environment in applications we are involved with, so this is a necessary configuration to support. Since we want to share the other consequences of the work we are doing, we want to make a single branch that is effective for all of the community and that means including Windows. Yes, the move to CMake is more complex, but the price is not too high, I think. However, if you would like to consider additional parallel support for make alone, then we might be able to add this to the branch for people who only want to compile on Linux (+ MacOS, maybe, although MacOS introduces more problems than Windows, we found!).

________________________________

**Pull request closed without merging**
