### PR TITLE
Increase the compatibility with modern compiler

### PR DESCRIPTION
**Pull request by teyssieuman**
I mainly replace the `std::auto_ptr` witch are deprecated since C++11 by `std::unique_ptr`.
This could also solve the issue on macos compilation.

### CODE REVIEW

**Comment by teyssieuman** [comment]
@DerekLong101 Is this  pull request able to integrate the master branch or should I modify it in something ? Perform some more verification ?

**Comment by DerekLong101** [comment]
I merged this in, but I need to watch to see whether it fixes or breaks the MacOS build - I think that was already broken for similar reasons - I am monitoring - this might need more work.

**Comment by teyssieuman** [comment]
Thank you @DerekLong101

**Comment by DerekLong101** [comment]
OK - it was broken for MacOS - I have fixed it properly by generalising the iterator_traits declaration in TimSupport.cpp - works for me now on Linux (need to wait for the auto build on MacOS and Windows).

**Comment by DerekLong101** [comment]
Seems to be building successfully for everything, so looks god, thanks!

**Comment by teyssieuman** [comment]
Great job !

**Comment by jan-dolejsi** [comment]
Thanks, @teyssieuman, I am stepping up the VAL version recommended by [VS Code PDDL Extension](https://marketplace.visualstudio.com/items?itemName=jan-dolejsi.pddl) to this version. Hoping this will be appreciated by the Mac and Linux users, where we have seen more crashes.

**Pull request merged**
